# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirátská strana
email: to@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
keywords: piráti, česká pirátská strana, svoboda, demokracie, piratsky, kontrola moci a mocných, zjednodušení státu pomocí technologií, ochranu občanů před šikanou, obranu svobody, černá na bílé, ivan bartoš, e-government, politika pro 21. století, 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pirati.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-pirati

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor
  - node_modules

sass:
    style: compressed

permalink: /tiskove-zpravy/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /program/:path/
  teams:
    output: true
    permalink: /pripoj-se/:title/
  elections:
    output: true
    permalink: /snemovna/:path/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "people, foto"
  -
    scope:
      path: "_program"
    values:
      layout: "page"
      rbar: "program"
  -
    scope:
      path: "_program/psp2017"
    values:
      layout: "page"
      rbar: "program program_item"
  -
    scope:
      path: "_program/komunal2018"
    values:
      layout: "page"
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar: "team-summary, teams-toc"
  -
    scope:
      path: "_elections"
    values:
      layout: "kandidatka"

calendar: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=kddvdvu3adcjef2kro4j6mm838%40group.calendar.google.com&amp;color=%232952A3&amp;ctz=Europe%2FPrague
fb: https://www.facebook.com/ceska.piratska.strana/
tw: PiratskaStrana

title-page:
  big:
    foto: /assets/img/miscellaneous/featured-dekujeme.gif
    alt: Výsledek voleb
    url: https://volebnimodely.pirati.cz/index_komunal.php
  left-top:
    text: Regiony
    url: regiony
    icon: fa fa-map-signs
  right-top:
    text: Naši lidé
    url: lide
    icon: fa fa-users
  left-bottom:
    text: Senát
    url: https://senat.pirati.cz
    icon: fa fa-user
  right-bottom:
    text: Program<br> Černé na bílém
    url: program
    icon: fa fa-newspaper-o u-rotate-345

emptyArray: []
